# Generated by Django 3.1.3 on 2020-11-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='todo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
